#!/bin/bash
LOG=/tmp/mylog.log
file=/home/zabbix_proxy.conf

if grep -q 187.121.26.34 $file; then

   echo "`date` :o ip ja e ajato" | tee -a $LOG
  exit 1
 else
        # call
        echo "`date` :o ip nao  e ajato, alterado" | tee -a $LOG
        sed -i 's/189.8.47.146/187.121.26.34/g' $file

 fi
